number_of_teachers: 16
group_names:
  - Statistics
  - Mathematics
  - Mechanics
  - Economics
  - Philosophy
  - Art Science
  - Computer Science
  - System Analysis
  - Applied Mathematics
max_students_per_group: 40
